package com.demo.entities;
// Generated Mar 7, 2024, 10:52:49 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * Inputifo generated by hbm2java
 */
@Entity
@Table(name = "inputifo", catalog = "warehousemanagement")
public class Inputifo implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Input input;
	private Product product;
	private Status status;
	private Suplier suplier;
	private int count;
	private String inputinfo;

	public Inputifo() {
	}

	public Inputifo(Account account, Input input, Product product, Status status, Suplier suplier, int count,
			String inputinfo) {
		this.account = account;
		this.input = input;
		this.product = product;
		this.status = status;
		this.suplier = suplier;
		this.count = count;
		this.inputinfo = inputinfo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accout_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "input_id", nullable = false)
	public Input getInput() {
		return this.input;
	}

	public void setInput(Input input) {
		this.input = input;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "suplier_id", nullable = false)
	public Suplier getSuplier() {
		return this.suplier;
	}

	public void setSuplier(Suplier suplier) {
		this.suplier = suplier;
	}

	@Column(name = "count", nullable = false)
	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	@Column(name = "inputinfo", nullable = false)
	public String getInputinfo() {
		return this.inputinfo;
	}

	public void setInputinfo(String inputinfo) {
		this.inputinfo = inputinfo;
	}

}
