package com.demo.entities;
// Generated Mar 7, 2024, 10:52:49 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Output generated by hbm2java
 */
@Entity
@Table(name = "output", catalog = "warehousemanagement")
public class Output implements java.io.Serializable {

	private Integer id;
	private int date;
	private Set<Outputinfor> outputinfors = new HashSet<Outputinfor>(0);

	public Output() {
	}

	public Output(int date) {
		this.date = date;
	}

	public Output(int date, Set<Outputinfor> outputinfors) {
		this.date = date;
		this.outputinfors = outputinfors;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "date", nullable = false)
	public int getDate() {
		return this.date;
	}

	public void setDate(int date) {
		this.date = date;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "output")
	public Set<Outputinfor> getOutputinfors() {
		return this.outputinfors;
	}

	public void setOutputinfors(Set<Outputinfor> outputinfors) {
		this.outputinfors = outputinfors;
	}

}
