package com.demo.entities;
// Generated Mar 7, 2024, 10:52:49 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * Picture generated by hbm2java
 */
@Entity
@Table(name = "picture", catalog = "warehousemanagement")
public class Picture implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String name;

	public Picture() {
	}

	public Picture(Product product, String name) {
		this.product = product;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
