package com.demo.entities;
// Generated Mar 7, 2024, 10:52:49 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;
/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "warehousemanagement")
public class Status implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Inputifo> inputifos = new HashSet<Inputifo>(0);
	private Set<Outputinfor> outputinfors = new HashSet<Outputinfor>(0);

	public Status() {
	}

	public Status(String name) {
		this.name = name;
	}

	public Status(String name, Set<Inputifo> inputifos, Set<Outputinfor> outputinfors) {
		this.name = name;
		this.inputifos = inputifos;
		this.outputinfors = outputinfors;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Inputifo> getInputifos() {
		return this.inputifos;
	}

	public void setInputifos(Set<Inputifo> inputifos) {
		this.inputifos = inputifos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Outputinfor> getOutputinfors() {
		return this.outputinfors;
	}

	public void setOutputinfors(Set<Outputinfor> outputinfors) {
		this.outputinfors = outputinfors;
	}

}
