package com.demo.entities;
// Generated Mar 7, 2024, 10:52:49 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Suplier generated by hbm2java
 */
@Entity
@Table(name = "suplier", catalog = "warehousemanagement")
public class Suplier implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;
	private String phone;
	private String email;
	private String moreinfor;
	private Date contactdate;
	private Set<Inputifo> inputifos = new HashSet<Inputifo>(0);

	public Suplier() {
	}

	public Suplier(String name, String address, String phone, String email, String moreinfor, Date contactdate) {
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.email = email;
		this.moreinfor = moreinfor;
		this.contactdate = contactdate;
	}

	public Suplier(String name, String address, String phone, String email, String moreinfor, Date contactdate,
			Set<Inputifo> inputifos) {
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.email = email;
		this.moreinfor = moreinfor;
		this.contactdate = contactdate;
		this.inputifos = inputifos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", nullable = false)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "moreinfor", nullable = false)
	public String getMoreinfor() {
		return this.moreinfor;
	}

	public void setMoreinfor(String moreinfor) {
		this.moreinfor = moreinfor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "contactdate", nullable = false, length = 10)
	public Date getContactdate() {
		return this.contactdate;
	}

	public void setContactdate(Date contactdate) {
		this.contactdate = contactdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "suplier")
	public Set<Inputifo> getInputifos() {
		return this.inputifos;
	}

	public void setInputifos(Set<Inputifo> inputifos) {
		this.inputifos = inputifos;
	}

}
