package com.demo.entities;
// Generated Mar 7, 2024, 10:52:49 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;

import jakarta.persistence.*;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "warehousemanagement")
public class Supplier implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;
	private String phone;
	private String email;
	private String information;
	private Date collaborationDay;

	public Supplier() {
	}

	public Supplier(String name, String address, String phone, String email, String information,
			Date collaborationDay) {
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.email = email;
		this.information = information;
		this.collaborationDay = collaborationDay;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", nullable = false, length = 250)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", nullable = false, length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "information", nullable = false, length = 250)
	public String getInformation() {
		return this.information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "collaboration day", nullable = false, length = 10)
	public Date getCollaborationDay() {
		return this.collaborationDay;
	}

	public void setCollaborationDay(Date collaborationDay) {
		this.collaborationDay = collaborationDay;
	}

}
