package com.demo.entities;

import jakarta.persistence.*;

// Generated Mar 7, 2024, 10:52:49 AM by Hibernate Tools 4.3.6.Final



/**
 * Userrole generated by hbm2java
 */
@Entity
@Table(name = "userrole", catalog = "warehousemanagement")
public class Userrole implements java.io.Serializable {

	private Integer id;
	private String name;

	public Userrole() {
	}

	public Userrole(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
